# https://docs.docker.com/compose/gettingstarted/
# https://www.jianshu.com/p/bf802ea2d7cf

version: '3.1'  #"登录容器请执行:rabbitmq-plugins enable rabbitmq_management 才可>使用WEB管理页面"
services:
  redis:
    # 指定镜像
    image: redis:4
    ports:
      # 端口映射
      - 6379:6379
    volumes:
      # 目录映射
      - ./redis/conf:/usr/local/etc/redis
      - ./redis/data:/data
    command:
      # 执行的命令
      redis-server --requirepass lyx147
    restart: always
  
  rmq:
    image: rabbitmq:3.6.9-management
    expose:
      - "15672"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    # hostname: rmq_node1
    environment:
      RABBITMQ_DEFAULT_VHOST: /ciwei
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: qweasd123
      RABBITMQ_LOGS: /var/lib/rabbitmq/rabbitmq.log
      RABBITMQ_SASL_LOGS: /var/lib/rabbitmq/rabbitmq-sasl.log
      RABBITMQ_ERLANG_COOKIE: LZJADKXKLULIXFKAALGX 
      TZ: Asia/Shanghai
#     extra_hosts:
#       - "rmq_node1:172.16.11.106"
#       - "rmq_node2:172.16.11.156"
#       - "rmq_node3:172.16.11.206"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
#      - /etc/hosts:/etc/hosts
    restart: always

  es:
    image: elasticsearch:7.6.2
    expose:
      - "9200"
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/logs:/usr/share/elasticsearch/logs
      - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
    ports:
      - "9200:9200"
    restart: always
  
  db:
    image: mysql:5.7
    expose:
      - "3306"
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ciwei_db_test
      - MYSQL_ROOT_PASSWORD=wcx9517530 
    restart: always
    
  web:
    build: .
    command: python /code/manager.py runserver
    volumes:
      - ./ciwei:/code
    ports:
      - "8999:8999"
    links:
      - db
      - es
      - redis
      - rmq
    restart: always