
# https://www.jianshu.com/p/bf802ea2d7cf 
# https://blog.csdn.net/bocai_xiaodaidai/article/details/92641534 多服务启动脚本
# https://docs.docker.com/compose/gettingstarted/ compose的安装与使用
# https://ecs.console.aliyun.com/#/server/region/cn-hangzhou 服务器
# https://github.com/jpetazzo/nsenter docker-enter命令
# https://www.shellhacks.com/docker-enter-container/ linux shell技巧

# 首先执行 sudo docker-compose build 构建不基于3rd镜像的web服务的镜像
# 然后执行 sudo docker-compose up  不加服务名会启动所有的服务。首次起服务时，会拉取基于3rd镜像的服务所需的镜像。
version: '3.1'  #"登录容器请执行:rabbitmq-plugins enable rabbitmq_management 才可>使用WEB管理页面"
services:
  # docker-enter ${container_id}
  # redis-cli 
  redis:
    # 指定镜像
    image: redis:4
    ports:
      # 端口映射
      - 6379:6379
    volumes:
      # 目录映射
      - ./redis/conf:/usr/local/etc/redis
      - ./redis/data:/data
    command:
      # 执行的命令
      redis-server --requirepass lyx147
    restart: always
  

  # docker exec -it ${rabbit_container_id} /bin/bash 不需要进入容器赋予用户权限
  # rabbitmqctl  set_permissions -p ciwei root '.*' '.*' '.*'
  rmq:
    image: rabbitmq:3.6.10-management
    expose:
      - "15672"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    environment:
      RABBITMQ_DEFAULT_VHOST: ciwei
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: qweasd123
      RABBITMQ_LOGS: /var/lib/rabbitmq/rabbitmq.log
      RABBITMQ_SASL_LOGS: /var/lib/rabbitmq/rabbitmq-sasl.log
      RABBITMQ_ERLANG_COOKIE: LZJADKXKLULIXFKAALGX 
      TZ: Asia/Shanghai
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    restart: always


# https://www.elastic.co/guide/en/elasticsearch/reference/6.4/docker.html#docker es官方docker配置的说明 
  es:
    image: elasticsearch:7.6.2
    expose:
      - "9200"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
    restart: always
  
  db:
    image: mysql:5.7
    expose:
      - "3306"
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ciwei_db_test
      - MYSQL_ROOT_PASSWORD=wcx9517530 
    restart: always
    
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./ciwei:/code
    ports:
      - "8999:8999"
    depends_on:
      - db
      - es
      - redis
      - rmq
    links:
      - db
      - es
      - redis
      - rmq
    restart: always