"""server_default migrate to default

Revision ID: 4ace4fb400ea
Revises: cf57fc493ec3
Create Date: 2020-02-27 08:34:25.816340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ace4fb400ea'
down_revision = 'cf57fc493ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'updated_time',
               existing_type=mysql.TIMESTAMP(),
               comment='最后一次更新时间',
               existing_comment='最近一次更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('product', 'cat_id',
               existing_type=mysql.INTEGER(display_width=11, unsigned=True),
               comment='周边类别id',
               existing_comment='周边类别',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'cat_id',
               existing_type=mysql.INTEGER(display_width=11, unsigned=True),
               comment='周边类别',
               existing_comment='周边类别id',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('order', 'updated_time',
               existing_type=mysql.TIMESTAMP(),
               comment='最近一次更新时间',
               existing_comment='最后一次更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
