"""20200227 migrate for index

Revision ID: cf57fc493ec3
Revises: 
Create Date: 2020-02-27 00:01:40.291380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf57fc493ec3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advs', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='通过审核的管理员id',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('advs', 'location',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'main_image',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'member_id',
               existing_type=mysql.INTEGER(display_width=11, unsigned=True),
               comment=None,
               existing_comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'pics',
               existing_type=mysql.VARCHAR(length=1000),
               comment=None,
               existing_comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'qr_code',
               existing_type=mysql.VARCHAR(length=200),
               comment=None,
               existing_comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='通过审核的管理员id',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('advs', 'stock',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'summary',
               existing_type=mysql.VARCHAR(length=10000),
               comment=None,
               existing_comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'tap_count',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'target_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'uu_id',
               existing_type=mysql.VARCHAR(length=80),
               comment=None,
               existing_comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'view_count',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('cart', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='插入时间',
               existing_comment='最后插入时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_cart_member_id'), 'cart', ['member_id'], unique=False)
    op.drop_index('idx_member_id', table_name='cart')
    op.alter_column('feedback', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='插入时间',
               existing_comment='最后插入时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('goods', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='插入时间',
               existing_comment='最后插入时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_goods_member_id'), 'goods', ['member_id'], unique=False)
    op.create_index(op.f('ix_goods_status'), 'goods', ['status'], unique=False)
    op.create_table_comment(
        'images',
        '图片表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('ix_order_callback_data_order_id'), 'order_callback_data', ['order_id'], unique=True)
    op.drop_index('order_id', table_name='order_callback_data')
    op.alter_column('order_product', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='插入时间',
               existing_comment='最后插入时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('order_product', 'order_id',
               existing_type=mysql.INTEGER(display_width=11, unsigned=True),
               comment='订单id',
               existing_comment='订单',
               existing_nullable=False)
    op.alter_column('order_product', 'product_id',
               existing_type=mysql.INTEGER(display_width=11, unsigned=True),
               comment='产品id',
               existing_comment='产品',
               existing_nullable=False)
    op.create_index(op.f('ix_order_product_member_id'), 'order_product', ['member_id'], unique=False)
    op.create_index(op.f('ix_order_product_order_id'), 'order_product', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_product_status'), 'order_product', ['status'], unique=False)
    op.alter_column('product', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='插入时间',
               existing_comment='最后插入时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_product_cat_id'), 'product', ['cat_id'], unique=False)
    op.create_index(op.f('ix_product_comments_member_id'), 'product_comments', ['member_id'], unique=False)
    op.create_index(op.f('ix_product_comments_order_id'), 'product_comments', ['order_id'], unique=False)
    op.drop_index('idx_member_id', table_name='product_comments')
    op.create_index(op.f('ix_product_sale_change_log_product_id'), 'product_sale_change_log', ['product_id'], unique=False)
    op.drop_index('idx_product_id', table_name='product_sale_change_log')
    op.create_index(op.f('ix_product_stock_change_log_product_id'), 'product_stock_change_log', ['product_id'], unique=False)
    op.drop_index('idx_product_id', table_name='product_stock_change_log')
    op.alter_column('qr_code', 'location',
               existing_type=mysql.VARCHAR(length=255),
               comment='会员收货地址',
               existing_comment='注册会员收货地址',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('qr_code', 'member_id',
               existing_type=mysql.INTEGER(display_width=11, unsigned=True),
               nullable=False,
               comment='会员id',
               existing_comment='二维码注册会员id')
    op.alter_column('qr_code', 'mobile',
               existing_type=mysql.VARCHAR(length=20),
               comment='会员手机号码',
               existing_comment='注册会员手机号码',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('qr_code', 'name',
               existing_type=mysql.VARCHAR(length=20),
               comment='会员姓名',
               existing_comment='注册会员的姓名，用于后期做匹配',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('qr_code', 'qr_code',
               existing_type=mysql.VARCHAR(length=255),
               comment='二维码图片',
               existing_comment='会员的小程序二维码图片',
               existing_nullable=False)
    op.create_index(op.f('ix_qr_code_openid'), 'qr_code', ['openid'], unique=False)
    op.alter_column('report', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='插入时间',
               existing_comment='最后插入时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('thank_order', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='插入时间',
               existing_comment='最后插入时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('thank_order', 'openid',
               existing_type=mysql.VARCHAR(length=32),
               comment='第三方id',
               existing_comment='下单微信用户',
               existing_nullable=False)
    op.alter_column('thanks', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='插入时间',
               existing_comment='最后插入时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thanks', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='最后插入时间',
               existing_comment='插入时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('thank_order', 'openid',
               existing_type=mysql.VARCHAR(length=32),
               comment='下单微信用户',
               existing_comment='第三方id',
               existing_nullable=False)
    op.alter_column('thank_order', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='最后插入时间',
               existing_comment='插入时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('report', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='最后插入时间',
               existing_comment='插入时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_qr_code_openid'), table_name='qr_code')
    op.alter_column('qr_code', 'qr_code',
               existing_type=mysql.VARCHAR(length=255),
               comment='会员的小程序二维码图片',
               existing_comment='二维码图片',
               existing_nullable=False)
    op.alter_column('qr_code', 'name',
               existing_type=mysql.VARCHAR(length=20),
               comment='注册会员的姓名，用于后期做匹配',
               existing_comment='会员姓名',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('qr_code', 'mobile',
               existing_type=mysql.VARCHAR(length=20),
               comment='注册会员手机号码',
               existing_comment='会员手机号码',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('qr_code', 'member_id',
               existing_type=mysql.INTEGER(display_width=11, unsigned=True),
               nullable=True,
               comment='二维码注册会员id',
               existing_comment='会员id')
    op.alter_column('qr_code', 'location',
               existing_type=mysql.VARCHAR(length=255),
               comment='注册会员收货地址',
               existing_comment='会员收货地址',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.create_index('idx_product_id', 'product_stock_change_log', ['product_id'], unique=False)
    op.drop_index(op.f('ix_product_stock_change_log_product_id'), table_name='product_stock_change_log')
    op.create_index('idx_product_id', 'product_sale_change_log', ['product_id'], unique=False)
    op.drop_index(op.f('ix_product_sale_change_log_product_id'), table_name='product_sale_change_log')
    op.create_index('idx_member_id', 'product_comments', ['member_id'], unique=False)
    op.drop_index(op.f('ix_product_comments_order_id'), table_name='product_comments')
    op.drop_index(op.f('ix_product_comments_member_id'), table_name='product_comments')
    op.drop_index(op.f('ix_product_cat_id'), table_name='product')
    op.alter_column('product', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='最后插入时间',
               existing_comment='插入时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_order_product_status'), table_name='order_product')
    op.drop_index(op.f('ix_order_product_order_id'), table_name='order_product')
    op.drop_index(op.f('ix_order_product_member_id'), table_name='order_product')
    op.alter_column('order_product', 'product_id',
               existing_type=mysql.INTEGER(display_width=11, unsigned=True),
               comment='产品',
               existing_comment='产品id',
               existing_nullable=False)
    op.alter_column('order_product', 'order_id',
               existing_type=mysql.INTEGER(display_width=11, unsigned=True),
               comment='订单',
               existing_comment='订单id',
               existing_nullable=False)
    op.alter_column('order_product', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='最后插入时间',
               existing_comment='插入时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('order_id', 'order_callback_data', ['order_id'], unique=True)
    op.drop_index(op.f('ix_order_callback_data_order_id'), table_name='order_callback_data')
    op.drop_table_comment(
        'images',
        existing_comment='图片表',
        schema=None
    )
    op.drop_index(op.f('ix_goods_status'), table_name='goods')
    op.drop_index(op.f('ix_goods_member_id'), table_name='goods')
    op.alter_column('goods', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='最后插入时间',
               existing_comment='插入时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('feedback', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='最后插入时间',
               existing_comment='插入时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('idx_member_id', 'cart', ['member_id'], unique=False)
    op.drop_index(op.f('ix_cart_member_id'), table_name='cart')
    op.alter_column('cart', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='最后插入时间',
               existing_comment='插入时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('advs', 'view_count',
               existing_type=mysql.INTEGER(display_width=11),
               comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'uu_id',
               existing_type=mysql.VARCHAR(length=80),
               comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'target_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'tap_count',
               existing_type=mysql.INTEGER(display_width=11),
               comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'summary',
               existing_type=mysql.VARCHAR(length=10000),
               comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'stock',
               existing_type=mysql.INTEGER(display_width=11),
               comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               comment='通过审核的管理员id',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('advs', 'qr_code',
               existing_type=mysql.VARCHAR(length=200),
               comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'pics',
               existing_type=mysql.VARCHAR(length=1000),
               comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'member_id',
               existing_type=mysql.INTEGER(display_width=11, unsigned=True),
               comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'main_image',
               existing_type=mysql.VARCHAR(length=100),
               comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'location',
               existing_type=mysql.VARCHAR(length=100),
               comment='通过审核的管理员id',
               existing_nullable=False)
    op.alter_column('advs', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               comment='通过审核的管理员id',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
